services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - frontend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.7" # Maksimum 70% CPU kullanabilir
          memory: "700M" # Maksimum 700 MB RAM kullanabilir

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.7" # Maksimum 70% CPU kullanabilir
          memory: "700M" # Maksimum 700 MB RAM kullanabilir
