services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - frontend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5" # Maksimum 50% CPU kullanabilir
          memory: "512M" # Maksimum 512 MB RAM kullanabilir

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5" # Maksimum 50% CPU kullanabilir
          memory: "512M" # Maksimum 512 MB RAM kullanabilir
