#!/bin/sh

# npm'in bulunduğu dizini PATH'e ekleyin
export PATH="$PATH:/usr/local/bin"

# Disabled test for now until we resolve an issue with client tests
# $(which npm) test 
$(which npm) run pre-commit
